### ISSUE TITLE
Issue in Alfred 4

### ISSUE THREAD

**Issue by LETRA** [dotson/Discogs-Explorer#6]
Hello. I am trying to make it work with Alfred 4 on macOS Catalina. Is there any solution in sight?

Thank you in advance.

**Comment by dotson** [comment]
Hi Letra, I just upgraded to Catalina and am working on updating all of my workflows now. I have a draft update for this one already and am running it through a few tests before releasing it.

**Comment by LETRA** [comment]
Thank you. I think it may be more useful to use your plugin than the tedious internal browser of JRiver Media Center for Mac.

All the best.

**Comment by dotson** [comment]
Really glad to hear that this is useful for you. I've just pushed an update that works with Music/Catalina, please let me know if you have any issues.

**Comment by LETRA** [comment]
Works very well.  I am put the label tag of my library's album list in the JRiver Media Center app. This app uses an internal chromium to display the webs of allmusic.com, discogs and also search for album data on google. JRiver has a retina lag (it is built through wine). By entering the data by hand in your Alfred plugin (artist & title album) I earn time and it is more dynamic than JRiver's lagging. I only find the problem that in an album with multiple versions I have to press "open in browser" to see the label (Blue Note, Columbia, Riverside for example). It is not a big problem, the plugin is very useful for me and I thank you for updating it and it works perfectly.

**Comment by LETRA** [comment]
Yes there is another problem. In some albums the plugin instead of displaying the data stops and Alfred proposes to search for the expression in google:

`Search Google for 'dex r11678736 ⇾' `

**Comment by dotson** [comment]
> I only find the problem that in an album with multiple versions I have to press "open in browser" to see the label (Blue Note, Columbia, Riverside for example). It is not a big problem, the plugin is very useful for me and I thank you for updating it and it works perfectly.

If I’m understanding you correctly, it sounds like adding a way to display an album’s record label would be useful to you?

That’d be a really great feature and I think it could be done relatively easily. I’ve been traveling for work this week, but I’ll look into this during the weekend and see what I can do.

**Comment by dotson** [comment]
> Yes there is another problem. In some albums the plugin instead of displaying the data stops and Alfred proposes to search the plugin expression in google:
> 
> `Search Google for 'dex r11678736 ⇾'`

Thanks for this! Using that error message, it looks like you were trying to search for “Nubya Garcia ‎– When We Are”

I should be able to use that info to hunt down whatever bug is causing the error. I’ll also give this a look in the next couple days and see what the issue is.

Thanks so much for your input, it’s really helpful.

**Comment by LETRA** [comment]
> If I’m understanding you correctly, it sounds like adding a way to display an album’s record label would be useful to you?
> 
> That’d be a really great feature and I think it could be done relatively easily. I’ve been traveling for work this week, but I’ll look into this during the weekend and see what I can do.

Particularly is the data I need to correctly organize my library. If you think it is useful and easy to implement, it is very good news for me!

**Comment by dotson** [comment]
Just pushed out update 1.40.01 that should address both items you mentioned above. 

- Added display of the record label for each release that shows in the first search window, see the screen shot below. Let me know if you'd like this formatted in a different way, I just picked this since it fit with the rest of the display, but other formatting is possible. 

- Fixed the bug that was causing the 'google search' error when searching for the Nubya Garcia release. This was a small variable definition typo that would apply to many other searches, so hopefully you don't see the error on anything else either. 

Please let me know if you find other bugs or if there are other features that would make this more useful for you! I'm not a professional programmer, so I can't promise I'll know how to make them happen, but I'm more than happy to try.

![Screen Shot 2019-11-02 at 9 48 16 AM](https://user-images.githubusercontent.com/4296385/68074342-24080c00-fd57-11e9-80f9-3b8cd6667c11.png)
